apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: whispering-stingray-nodejs
  janus-idp.io/tekton: whispering-stingray-nodejs
  backstage.io/kubernetes-id: whispering-stingray-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: whispering-stingray-nodejs
resources: 
- deployment.yaml
- route.yaml
- service.yaml
