apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: whispering-stingray-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whispering-stingray-nodejs 
  name: whispering-stingray-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: whispering-stingray-nodejs 
